### ISSUE TITLE
About the GMC loss function

### ISSUE THREAD

**Issue by jasperhyp** [miguelsvasco/gmc#1]
Dear Authors-- Thanks for sharing the code!  I really enjoyed your paper.  There is one issue I'm not sure if I understood-- In your paper, the CL loss function seems to be an adapted version of InfoNCE, in that instead of using symmetric construction specified in SimCLR, you used a construction where (for each single modality) each pair augmentations (i.e. $z_{1:M}^i$ and $z_m^i$) is passed as positive only once, and the denominator becomes the sum of all negatives surrounding this pair ( $\sum_{j\neq i}{s_{m, 1:M}(i,j)+s_{m,m}(i,j)+s_{1:M, 1:M}(i,j)}$ , excluding the positive pair), which looks really interesting.  However, in the [implementation](https://github.com/miguelsvasco/gmc/blob/main/gmc_code/unsupervised/architectures/models/gmc.py#L55), it looks like the loss is still the same as SimCLR, where the pair augmentation is passed as positive twice and each time the denominator is different, using negative samples corresponding to either augmentation only (i.e. $\sum_{j\neq i}{(s_{m, 1:M}(i,j)+s_{m,m}(i,j))}+s_{m, 1:M}(i,i)$ for the $m$-centric pass and vice versa for the other pass, and including the positive pair in the summation).  Did I miss anything?

Thanks for your attention!

**Comment by petrapoklukar** [comment]
Hi @jasperhyp, 

apologies for our late reply and thanks for the interest in our work!

What you are saying is correct, as stated in the paper our loss function extends InfoNCE to the multimodal setting. This means that the loss is calculated for the positive pairs $(z_m^i, z_{1:M}^i)$ and $(z_{1:M}^i, z_m^i)$ in the same forward pass. The first pair is contrasted with the negative pairs $\sum_{i  \neq j} s_{m, m}(i, j) + \sum_j s_{m, 1:M}(i, j)$, whereas the second pair is contrasted with $\sum_{i  \neq j} s_{1:M, 1:M}(i, j) + \sum_j s_{1:M, m}(i, j)$. Thank you for pointing out this typo in the paper, we will update it accordingly.

Hope this answers your question, 
Petra and Miguel
