### ISSUE TITLE
projection head for modality-specific representations

### ISSUE THREAD

**Issue by suminRoh** [miguelsvasco/gmc#3]
Thank you for your invaluable contribution to this research! I have a question regarding the implementation details described in the paper.

In the paper, it is stated that the shared projection head 𝑔() maps the intermediate representations of both the modality-specific representations and the joint representations. However, upon reviewing the code at supervised/architectures/models/gmc.py lines 60-61, it appears that the modality-specific representations only pass through the modality-specific encoder, while the joint representations are the only ones that pass through the shared projection head.

This seems to be inconsistent with the paper's description of the geometric alignment of joint representations with each modality-specific representation. Could you please clarify this aspect of the implementation? I would greatly appreciate your insight on this matter.

Thank you very much for your time and assistance.

**Comment by miguelsvasco** [comment]
Hi there!
Just to recap the code: `self.encoder` corresponds to the shared-projection head and `self.processors` corresponds to the modality-specific encoders.
 https://github.com/miguelsvasco/gmc/blob/4abd628c935b0768f1aa18864fbd885b76bebe02/gmc_code/supervised/architectures/models/gmc.py#L60-L67
 
As you can see, both the joint and modality-specific representations pass through the shared projection head (line 60 and line 66, respectively)
